# .github/workflows/c-check.yml
name: C Code Lint

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install GCC and Cppcheck
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cppcheck

    - name: Static analysis using Cppcheck
      run: |
        cppcheck --enable=all --inconclusive --error-exitcode=1 .
